Script started on 2016年03月02日 (週三) 19時56分53秒
]0;zeroplusone@2015cpp: ~/lab1[01;32mzeroplusone@2015cpp[00m:[01;34m~/lab1[00m$ whoami'[K; pwd
zeroplusone
/home/zeroplusone/lab1
]0;zeroplusone@2015cpp: ~/lab1[01;32mzeroplusone@2015cpp[00m:[01;34m~/lab1[00m$ git config -l;[K
user.name=zeroplusone
user.email=a711186@gmail.com
]0;zeroplusone@2015cpp: ~/lab1[01;32mzeroplusone@2015cpp[00m:[01;34m~/lab1[00m$ git clone https://github.com/zeroplusone/pd2_lab1.git
Cloning into 'pd2_lab1'...
warning: You appear to have cloned an empty repository.
]0;zeroplusone@2015cpp: ~/lab1[01;32mzeroplusone@2015cpp[00m:[01;34m~/lab1[00m$ exit

Script done on 2016年03月02日 (週三) 19時57分18秒
